POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "name":"PC da Nasa RGB JAMES WEB 1.10",
  "price": 5000000000000000000000000000
}

###

# GET http://localhost:8080/products/83c85034-2a53-4835-83f0-dfc04c3bda65 HTTP/1.1
GET http://localhost:8080/products/fdb5892a-4928-40a5-b0ae-b2000e3dadf8 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8080/products/fdb5892a-4928-40a5-b0ae-b2000e3dadf8 HTTP/1.1
Content-Type: application/json

{
  "name":"PC da Nasa RGB JAMES WEB 9.1 Atualizado",
  "price": 500
}

###

DELETE http://localhost:8080/products/fdb5892a-4928-40a5-b0ae-b2000e3dadf8 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNjIxMTcsInN1YiI6ImYxNmEwYjFmLTc1MGEtNDg3Yi1iZDI4LTU4OWE4YTkwYTAwMSJ9.ZEDxf_qVmQ229ptNwXwuh02ZZXw8kAC9TCXa_akarII
